"""ReconForge AD Module - Legacy AD summary reporter.

Author: Andrews Ferreira

Generates a markdown summary of all phase results, attack surface,
and domain intelligence — preserves the legacy output format.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List

from modules.ad.reporting.base import ReporterBase


class ADSummaryReporter(ReporterBase):
    """Generates the legacy ad_summary.md output."""

    def generate(self, data: Dict[str, Any]) -> str:
        domain = data.get("domain", "Not discovered")
        target = data.get("target", "unknown")
        dc_ip = data.get("dc_ip", target)
        phases = data.get("phases", {})
        attack_paths = data.get("attack_paths", [])

        lines = [
            "# Active Directory Reconnaissance Summary\n",
            f"**Domain:** {domain or 'Not discovered'}",
            f"**Target DC:** {target} ({dc_ip})",
            f"**Scan Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Author:** Andrews Ferreira", "",
        ]

        for phase_key, title in [
            ("passive", "Phase 1: Passive Reconnaissance"),
            ("identity", "Phase 2: Identity Enumeration"),
            ("configuration", "Phase 3: Configuration Enumeration"),
            ("delegation", "Phase 4: Delegation Discovery"),
            ("bloodhound", "Phase 5: Bloodhound Collection"),
        ]:
            phase_data = phases.get(phase_key, {})
            if phase_data:
                lines.append(f"## {title}\n")
                for k, v in phase_data.items():
                    if k in ("phase", "target", "success"):
                        continue
                    if isinstance(v, (list, dict)) and len(str(v)) > 200:
                        lines.append(
                            f"- **{k}:** {len(v) if isinstance(v, list) else 'present'}"
                        )
                    else:
                        lines.append(f"- **{k}:** {v}")
                lines.append("")

        lines.append("## Attack Surface Summary\n")
        if attack_paths:
            lines.append(f"**{len(attack_paths)} attack path(s) identified:**\n")
            for path in attack_paths:
                lines.append(
                    f"- **{path.name}** [{path.risk.upper()}]: {path.description}"
                )
        else:
            lines.append("No automated attack paths identified.\n")

        lines.append(
            f"\n---\n*Generated by ReconForge AD Module v1.0 — Author: Andrews Ferreira*\n"
        )
        return "\n".join(lines)
