"""ReconForge AD Reporter — Overall AD attack surface summary.

Author: Andrews Ferreira
"""

from datetime import datetime
from typing import Any, Dict
from modules.ad.reporting.base import ReporterBase


class AttackSurfaceReporter(ReporterBase):
    """Generate overall AD attack surface report."""

    REPORTER_NAME = "attack_surface"

    def generate(self, data: Dict[str, Any], **kwargs) -> str:
        """Generate attack surface summary markdown."""
        target = data.get("target", "")
        domain = data.get("domain", "Not discovered")
        dc_ip = data.get("dc_ip", target)
        opsec_mode = data.get("opsec_mode", "normal")
        authenticated = data.get("authenticated", False)
        severity_counts = data.get("severity_counts", {})
        loot_summary = data.get("loot_summary", {})
        total = sum(severity_counts.values())

        lines = [
            "# ReconForge Quick Report - AD Module\n",
            f"**Target:** {target}",
            f"**Domain:** {domain}",
            f"**Domain Controller:** {dc_ip}",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**OPSEC Mode:** {opsec_mode}",
            f"**Authenticated:** {'Yes' if authenticated else 'No'}",
            f"**Author:** Andrews Ferreira",
            "",
            "## Executive Summary\n",
            f"Active Directory reconnaissance of **{domain or target}** "
            f"identified **{total}** findings:\n",
        ]

        for sev in ["critical", "high", "medium", "low", "info"]:
            count = severity_counts.get(sev, 0)
            icon = {
                "critical": "🔴", "high": "🟠", "medium": "🟡",
                "low": "🔵", "info": "⚪",
            }.get(sev, "⚪")
            lines.append(f"- {icon} **{sev.upper()}:** {count}")

        lines.append("")
        lines.append("## Loot Summary\n")
        for ltype, count in loot_summary.items():
            lines.append(f"- **{ltype}:** {count} item(s)")

        # Critical/high findings
        critical_high = data.get("critical_high_findings", [])
        if critical_high:
            lines.append("\n## Critical & High Findings\n")
            for f in critical_high:
                lines.append(f"### [{f.get('severity','').upper()}] {f.get('description','')}")
                lines.append(f"- **Target:** {f.get('target','')}")
                lines.append(f"- **Confidence:** {f.get('confidence','')}")
                if f.get("recommendation"):
                    lines.append(f"- **Recommendation:** {f['recommendation']}")
                lines.append("")

        # Attack paths
        attack_paths = data.get("attack_paths", [])
        if attack_paths:
            lines.append("## Identified Attack Paths\n")
            for path in attack_paths:
                lines.append(f"### {path.name} [{path.risk.upper()}]")
                lines.append(f"{path.description}\n")
                for i, step in enumerate(path.steps, 1):
                    lines.append(f"{i}. {step}")
                lines.append("")

        # Suggestions
        suggestions = data.get("suggestions", [])
        if suggestions:
            lines.append("## Suggested Next Steps\n")
            for s in suggestions[:10]:
                lines.append(f"- [{s.get('priority','medium').upper()}] `{s.get('command','')}`")
                lines.append(f"  - {s.get('justification','')}")

        lines.append(
            f"\n---\n*Generated by ReconForge v1.0 release on "
            f"{datetime.now():%Y-%m-%d %H:%M:%S}*\n"
        )

        return "\n".join(lines)
