"""ReconForge AD Reporter — Attack path visualization.

Author: Andrews Ferreira
"""

from datetime import datetime
from typing import Any

from modules.ad.attack_paths.base import AttackChain, NextStepSuggestion
from modules.ad.reporting.base import ReporterBase


class AttackPathReporter(ReporterBase):
    """Generate attack path visualization report."""

    REPORTER_NAME = "attack_paths"

    def generate(self, data: dict[str, Any], **kwargs) -> str:
        """Generate attack path markdown report."""
        domain = data.get("domain", "Unknown")
        target = data.get("target", "")
        chains: list[AttackChain] = data.get("chains", [])
        suggestions: list[NextStepSuggestion] = data.get("suggestions", [])

        lines = [
            "# Active Directory Attack Paths\n",
            f"**Domain:** {domain}",
            f"**Target DC:** {target}",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Total Paths:** {len(chains)}",
            "",
        ]

        # Group by risk
        for risk_level in ["critical", "high", "medium", "low"]:
            risk_chains = [c for c in chains if c.risk == risk_level]
            if not risk_chains:
                continue

            icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵"}.get(risk_level, "⚪")
            lines.append(f"## {icon} {risk_level.upper()} Risk Paths ({len(risk_chains)})\n")

            for chain in risk_chains:
                lines.append(f"### {chain.name}")
                lines.append(f"*{chain.description}*\n")

                if chain.source or chain.target:
                    lines.append(f"**Path:** `{chain.source or '?'}` → `{chain.target or '?'}`\n")

                lines.append("**Steps:**")
                for i, step in enumerate(chain.steps, 1):
                    lines.append(f"{i}. {step}")

                if chain.prerequisites:
                    lines.append(f"\n**Prerequisites:** {', '.join(chain.prerequisites)}")
                if chain.references:
                    lines.append(f"**References:** {', '.join(chain.references)}")
                lines.append("")

        # Operator suggestions
        if suggestions:
            lines.append("## Suggested Next Steps\n")
            lines.append("| Priority | Command | Justification |")
            lines.append("|----------|---------|---------------|")
            for s in suggestions:
                lines.append(
                    f"| {s.priority.upper()} | `{s.command}` | {s.justification} |"
                )
            lines.append("")

        lines.append(
            "\n---\n*Generated by ReconForge AD Module — "
            "Author: Andrews Ferreira*\n"
        )
        return "\n".join(lines)
