"""ReconForge AD Reporter — High-value target identification.

Author: Andrews Ferreira
"""

from datetime import datetime
from typing import Any, Dict, List
from modules.ad.reporting.base import ReporterBase


class HighValueTargetsReporter(ReporterBase):
    """Generate high-value target report."""

    REPORTER_NAME = "high_value_targets"

    def generate(self, data: Dict[str, Any], **kwargs) -> str:
        """Generate HVT markdown report."""
        domain = data.get("domain", "Unknown")
        target = data.get("target", "")

        lines = [
            "# Active Directory High-Value Targets\n",
            f"**Domain:** {domain}",
            f"**Target DC:** {target}",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ]

        # Domain Admins
        da_users = data.get("da_users", [])
        if da_users:
            lines.append("## Domain Admin Members\n")
            for u in da_users:
                lines.append(f"- `{u}`")
            lines.append("")

        # Privileged users
        priv = data.get("privileged_users", [])
        if priv:
            lines.append("## Privileged Users\n")
            for u in priv[:30]:
                lines.append(f"- `{u}`")
            lines.append("")

        # Kerberoastable
        kerb = data.get("kerberoastable", [])
        if kerb:
            lines.append("## Kerberoastable Accounts\n")
            for u in kerb[:20]:
                lines.append(f"- `{u}`")
            lines.append("")

        # AS-REP roastable
        asrep = data.get("asreproastable", []) or data.get("asrep_users", [])
        if asrep:
            lines.append("## AS-REP Roastable Accounts\n")
            for u in asrep[:20]:
                name = u if isinstance(u, str) else u.get("username", "")
                lines.append(f"- `{name}`")
            lines.append("")

        # Unconstrained delegation
        uc = data.get("unconstrained_computers", [])
        if uc:
            lines.append("## Unconstrained Delegation Hosts\n")
            for h in uc:
                lines.append(f"- `{h}`")
            lines.append("")

        # Domain controllers
        dcs = data.get("domain_controllers", [])
        if dcs:
            lines.append("## Domain Controllers\n")
            for dc in dcs:
                lines.append(f"- `{dc}`")
            lines.append("")

        # All HVTs
        hvts = data.get("high_value_targets", [])
        if hvts:
            lines.append("## All High-Value Targets\n")
            lines.append("| Name | Type | Reasons |")
            lines.append("|------|------|---------|")
            for hvt in hvts[:50]:
                reasons = ", ".join(hvt.get("reasons", []))
                lines.append(f"| {hvt.get('name','')} | {hvt.get('type','')} | {reasons} |")
            lines.append("")

        lines.append(
            f"\n---\n*Generated by ReconForge AD Module — "
            f"Author: Andrews Ferreira*\n"
        )
        return "\n".join(lines)
