"""ReconForge AD Reporter — Remediation recommendations.

Author: Andrews Ferreira
"""

from datetime import datetime
from typing import Any, Dict, List
from modules.ad.reporting.base import ReporterBase


class RemediationReporter(ReporterBase):
    """Generate remediation recommendation report."""

    REPORTER_NAME = "remediation"

    def generate(self, data: Dict[str, Any], **kwargs) -> str:
        """Generate remediation recommendations markdown."""
        domain = data.get("domain", "Unknown")
        target = data.get("target", "")
        findings = data.get("findings", [])

        lines = [
            "# Active Directory Remediation Recommendations\n",
            f"**Domain:** {domain}",
            f"**Target DC:** {target}",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Author:** Andrews Ferreira",
            "",
        ]

        # Group by severity
        for sev in ["critical", "high", "medium", "low"]:
            sev_findings = [f for f in findings if f.get("severity") == sev]
            if not sev_findings:
                continue

            icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵"}.get(sev, "⚪")
            lines.append(f"## {icon} {sev.upper()} Priority Remediations\n")

            for f in sev_findings:
                desc = f.get("description", "")
                rec = f.get("recommendation", "")
                refs = f.get("references", [])

                lines.append(f"### {desc}")
                if rec:
                    lines.append(f"**Remediation:** {rec}\n")
                if refs:
                    lines.append("**References:**")
                    for ref in refs:
                        lines.append(f"- {ref}")
                lines.append("")

        # General hardening recommendations
        lines.append("## General AD Hardening Recommendations\n")
        lines.append("1. **Password Policy:** Minimum 12 characters, complexity enabled, lockout threshold of 5")
        lines.append("2. **SMB Signing:** Require SMB signing on all domain controllers and servers")
        lines.append("3. **LDAP Signing:** Require LDAP signing and channel binding")
        lines.append("4. **Delegation:** Replace unconstrained with constrained delegation; audit RBCD")
        lines.append("5. **Pre-auth:** Enable Kerberos pre-authentication for all accounts")
        lines.append("6. **SPNs:** Use gMSA for service accounts; remove unnecessary SPNs")
        lines.append("7. **MachineAccountQuota:** Set to 0 to prevent standard user computer creation")
        lines.append("8. **Admin Tiering:** Implement tiered admin model (Tier 0/1/2)")
        lines.append("9. **Monitoring:** Deploy honeypot accounts and monitor for Kerberoasting/AS-REP")
        lines.append("10. **Trusts:** Audit trusts; enable SID filtering on external trusts")

        lines.append(
            f"\n---\n*Generated by ReconForge AD Module — "
            f"Author: Andrews Ferreira*\n"
        )
        return "\n".join(lines)
